version: '3.5'

services:
  postgres:
    container_name: tonistore
    image: postgres
    environment:
      POSTGRES_DB: tonistore
      POSTGRES_USER: ${POSTGRES_USER:-tonistoreadmin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tonistoredb}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24

volumes:
  postgres: